print('===== Desafio 02 =====')
dia = input('Qual é o dia do teu nascimento?')
mes = input('Qual é o mês do teu nascimento?')
ano = input('Qual é o ano do teu nascimento?')
print('Você nasceu no dia',dia,'de',mes,'de',ano,'. Correto?')
